# Generated by Django 3.2.7 on 2021-09-07 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='Rut')),
                ('fecha_actual', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('edad', models.PositiveIntegerField(default=0)),
                ('altura', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('peso', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('remuneracion', models.DecimalField(decimal_places=1, default=0.0, max_digits=20)),
                ('estado', models.BooleanField(default=True)),
                ('sexo', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados_fotos/%Y/%m/%d')),
                ('cv', models.ImageField(blank=True, null=True, upload_to='empleados_cv/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
                'ordering': ['-id'],
            },
        ),
    ]
