# Generated by Django 3.2.6 on 2021-09-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valdivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del tipo de Empleado')),
            ],
            options={
                'verbose_name': 'TipoDeEmpleado',
                'verbose_name_plural': 'TiposDeEmpleados',
                'db_table': 'TipoDeEmpleado',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdivia.tiposdeempleados'),
        ),
    ]
