# Generated by Django 3.2.6 on 2021-09-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdivia', '0003_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='categoria',
            field=models.ManyToManyField(to='valdivia.Categorias'),
        ),
    ]
